# Generated by Django 4.2.5 on 2023-09-24 01:29

import BookStore.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Biography', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=200)),
                ('Publication_Date', models.CharField(max_length=200)),
                ('Language', models.CharField(max_length=200)),
                ('Average_Rating', models.FloatField(validators=[BookStore.models.Book.validate_max_rating])),
                ('Quantity', models.IntegerField()),
                ('Cover_Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField(max_length=200)),
                ('authors', models.ManyToManyField(related_name='books', to='BookStore.author')),
            ],
            options={
                'db_table': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Phone_Number', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateTimeField()),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=200)),
                ('OrderItems', models.CharField(max_length=200)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='BookStore.customer')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Contact_Info', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Publishers',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ReviewText', models.TextField(max_length=200)),
                ('Date_Posted', models.DateTimeField()),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.book')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.customer')),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
        migrations.DeleteModel(
            name='BookStoreItems',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='BookStore.genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.ManyToManyField(related_name='books', to='BookStore.publisher'),
        ),
    ]
