# Generated by Django 4.2.5 on 2023-09-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=200)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=65)),
                ('Description', models.CharField(max_length=200)),
                ('Publication_Date', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=200)),
                ('Quantity', models.IntegerField()),
                ('Language', models.CharField(max_length=200)),
                ('Publisher', models.CharField(max_length=200)),
                ('Cover_Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Average_Rating', models.FloatField()),
                ('Tags', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Books',
            },
        ),
        migrations.DeleteModel(
            name='BookStoreItems',
        ),
    ]
