# Generated by Django 4.2.5 on 2023-09-22 21:53

import BookStore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_books_delete_bookstoreitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=200)),
                ('Publication_Date', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=200)),
                ('Language', models.CharField(max_length=200)),
                ('Publisher', models.CharField(max_length=200)),
                ('Average_Rating', models.FloatField(validators=[BookStore.models.Book.validate_max_rating])),
                ('Quantity', models.IntegerField()),
                ('Cover_Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField(max_length=200)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
