# Generated by Django 4.2.5 on 2023-09-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0003_book_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Biography', models.CharField(max_length=200)),
                ('Books', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Phone_Number', models.CharField(max_length=200)),
                ('Orders', models.CharField(max_length=200)),
            ],
             options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Books', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=200)),
                ('OrderDate', models.DateTimeField()),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=200)),
                ('OrderItems', models.CharField(max_length=200)),
            ],
             options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Books', models.CharField(max_length=200)),
                ('Contact_Info', models.CharField(max_length=200)),
            ],
             options={
                'db_table': 'Publisher',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book', models.CharField(max_length=200)),
                ('Customer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Rating', models.CharField(max_length=200)),
                ('ReviewText', models.TextField(max_length=200)),
                ('Date_Posted', models.DateTimeField()),
            ],
             options={
                'db_table': 'Review',
            },
        ),
    ]
