# Generated by Django 4.2.5 on 2023-09-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0004_author_customer_genre_order_publisher_review'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Books',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publisher',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
